### ISSUE TITLE
docs: Setup jupyterbook

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/MAWpy#4]
## Overview

Currently, there is only one notebook called demo in the `docs` folder and there is no system to render any docs. Let's setup [Jupyterbook](https://jupyterbook.org/en/stable/intro.html) so that we can add additional docs later. Instruction to create a sample book and fill with necessary details can be found in: https://jupyterbook.org/en/stable/start/create.html

## Action Items
- [x] Add `_config.yml` file
- [x] Add `_toc.yml` file
- [x] Add initial `intro.md`

**Comment by anujsinha3** [comment]
https://mawpy.readthedocs.io/en/latest/intro.html
