### ISSUE TITLE
Changes to incremental clustering algorithm

### ISSUE THREAD

**Issue by Anurag19101996** [uw-ssec/MAWpy#46]
Hello,

Below are the proposed changes to the older incremental clustering algorithm. Could you update the changes in the new code:

1.  In the beginning of the algorithm, instead of checking the presence of duration_constraint to prepare loc4cluster list, we want to create a single list which consists of all unique GPS coordinates. A proposed example is given below-
Before: https://github.com/uw-ssec/MAWpy/blob/main/src/mawpy/IncrementalClustering.py#L124-L140
After proposed change:
```python
 loc4cluster = list(set([(trace[3], trace[4]) for d in user for trace in user[d]]))
`````

2. After the clusters are formed, we only wish to keep those clusters whose stay duration is greater than or equal to the duration constraint. A proposed example is shown below-
After the line https://github.com/uw-ssec/MAWpy/blob/main/src/mawpy/IncrementalClustering.py#L377, could we add a condition to keep only those clusters whose stay_dur columns >= duration_constraint?

The remaining points from a_stay whose stay_dur do not meet the above condition can be stored in a separate list. In case in the future if these stored transient points are required, we can use them as well.

Thanks!
@qzchen-uw @gracejia513 @anujsinha3 @carlosgjs

**Comment by anujsinha3** [comment]
Hi @Anurag19101996,

For the second point, I had a logical question on the suggested change:
As per my understanding, `a_stay` is a collection of trace points that should have a single calculated value of stay duration for the collection.

Based on this, we need to append only those `a_stay` that satisfy the condition `a_stay.stay_duration > duration_constraint` 

But currently, in the old [code-chunk](https://github.com/uw-ssec/MAWpy/blob/main/src/mawpy/IncrementalClustering.py#L366-L376), there is no code-logic/variable that stores or calculates the stay_duration for 'a_stay'. Can you confirm what should be done here?

**Comment by Anurag19101996** [comment]
Hi @anujsinha3,

I skipped telling you this in the initial comment. For a cluster the stay duration will be the time difference between the first trace and the last trace, where the first and last trace are decided by sorting the traces by datetime in ascending order (if its not sorted from before).

Let me know if that helps!

**Comment by anujsinha3** [comment]
please test and let me know if any issue is found.
