### ISSUE TITLE
query: how to handle non-mandatory columns in address oscillation.

### ISSUE THREAD

**Issue by anujsinha3** [uw-ssec/MAWpy#52]
While refactoring AddressOscillation.py and oscillation_type1.py, we observed that the code depends on columns that are not in the mandatory column list: [user_id, orig_lat, orig_long, unix_start_t].

These columns are: [stay_lat, stay_long, stay_unc,  stay_dur, orig_unc].

Currently, the code assumes the value for columns [stay_lat, stay_long, 'stay_dur', 'stay_unc'] to be set as -1 but never missing from the csv file.

- While it is possible to put a conditional check in the code for when [stay_lat, stay_long, 'stay_dur'] columns are missing, and retrieve values from [orig_lat, orig_long, 1] respectively. Can you please confirm if this is the expected behavior?
https://github.com/uw-ssec/MAWpy/blob/main/src/mawpy/oscillation_type1.py#L43-L51
https://github.com/uw-ssec/MAWpy/blob/main/src/mawpy/oscillation_type1.py#L55-L57

- Also, the code tries to retrieve the value of 'orig_unc' when 'stay_unc' is -1. Whereas, as per our discussion 'orig_unc' is also an optional column. What should be the expected behavior in this case?
https://github.com/uw-ssec/MAWpy/blob/main/src/mawpy/oscillation_type1.py#L52-L54

assignees: @gracejia513 @@Anurag19101996

for awareness: @carlosgjs @lsetiawan

**Comment by gracejia513** [comment]
We discussed this with @qzchen-uw , and the decision is that the address oscillation should work regardless of whether the input has these columns: stay_lat, stay_long, stay_unc, stay_dur, orig_unc. 

So for the first bullet point, I think we want the behavior to be: if no clustering is run prior to address oscillation, we use orig_lat and orig_long; if clustering is run prior to address oscillation, se use stay_lat, stay_long, stay_dur, and stay_unc. 

And for the second bullet point, I think the unc, whether orig_unc or stay_unc, is saved to a variable rad (https://github.com/uw-ssec/MAWpy/blob/f6132307ec88ddbb89e37cd5a2e8eba36687434e/src/mawpy/oscillation_type1.py#L52-L54), and rad was never referenced again later in the code. Rad was then saved to tracelist (a nested list) as the sixth item of the sublist (and the fourth and fifth items are lat and long). So to reference rad, one might use a syntax of tracelist[i][5]. And I think tracelist[i][5] was only involved in checking whether two observations are the same by comparing the values of tracelist[i][3:5]. And this comparison might be replaced by tracelist[i][3:4], which only involves checking the lat (set to orig_lat previously), and long (set to orig_long previously).
@qzchen-uw and @Anurag19101996 please edit as you see fit.
