### ISSUE TITLE
tests: write unite tests for common.py

### ISSUE THREAD

**Issue by anujsinha3** [uw-ssec/MAWpy#72]
There are four functions in the file [common.py](https://github.com/uw-ssec/MAWpy/blob/main/src/mawpy/utilities/common.py).

The task is to develop unit test cases for these functions:

- _mean_ignore_minus_ones()
- _merge_stays()
- get_combined_stay()
- get_stay_groups()

If possible, use the hypothesis framework as used in [test_io.py](https://github.com/uw-ssec/MAWpy/blob/main/tests/test_io.py)

Guidelines for contributing to UW-SSEC projects:
https://rse-guidelines.readthedocs.io/en/latest/fundamentals/git-github.html#open-source-development-with-git-and-github

**Comment by parvatijay2901** [comment]
Hi @lsetiawan,
I wrote the unit tests for this function (https://github.com/parvatijay2901/MAWpy/commit/f9bc5c3d0297a315915ba50046d7e6127b7e1dff), however, I somehow missed the description and just realized today morning that I need to have it using hypothesis framework. I could only write test cases for _mean_ignore_minus_ones() and _merge_stays() in the given time. I will have it for the other 2 functions and upload it by tonight. 

I hope it is fine!

**Comment by parvatijay2901** [comment]
I have a few questions:
1. I added a few ValueErrors and KeyErrors in common.py to make sure that the data frame is in the format we need (i.e., not empty, have STAY_LAT, STAY_LONG, STAY columns, etc.). When I imported the function (in common.py) to a different file (test_common.py) and passed an empty array, I expected that a ValueError would be raised, however, I do not see it being raised:
![1](https://github.com/user-attachments/assets/40f5dc44-6806-42cd-82e5-ef68d13cea3c)

On the other hand, if I have the function and test in the same file (i.e., test_common.py in this case), then the error is raised as expected,
![2](https://github.com/user-attachments/assets/8b469f0c-1f3f-4096-bfbd-d6cc0b63a20e)

Does this have anything to do with pytest? I did a basic Google search to find the reason, but couldn't!

2. get_combined_stay() requires a threshold value - what will be an ideal range to test?

3. I couldn't think of any cases to test get_combined_stay() properly - other than checking if the DataFrame is empty/has the same columns as we need/output dtype is Pandas DataFrame/.. are there any other cases that I can include here to test it better?

Thanks!

**Comment by lsetiawan** [comment]
Hi @parvatijay2901. Thanks for taking a look at this issue and creating a PR to resolve it. From here on, I'll defer to @anujsinha3 to answer your questions as well as review your PR. He is the main developer for this package. 😄

**Comment by anujsinha3** [comment]
Hi @parvatijay2901, I see you have raised the PR, just wanted to confirm if you are still facing this issue? Happy to help on this or any other issue. 🙂

**Comment by parvatijay2901** [comment]
Hey @anujsinha3,
I have removed (1), however, I still don't know the reason!
If you could also provide me more on (2) and (3), I can update the test_common.py if required!
Thanks :))

**Comment by anujsinha3** [comment]
1. For one, that's odd. It's difficult to tell without looking at your environment setup. 

For 2 and 3:

The function merges chronologically sorted pandas data frame with columns ['stay', 'stay_lat', 'stay_long'] where the distance between the mean_lat and mean_long of two consecutive stays for a user is less than the threshold.

By merging, it updates two different stays(multiple rows of entries with two unique values in 'stay' column) to have the same updated value for the 'stay' column based on certain conditions. The logic is mentioned in the function docstring.

The ideal value of the testing threshold should be any positive value (for simplicity we can assume the max to be 10).

PS: This is a bit more complicated function to test - we need not require to wait on this to merge the existing PR

**Comment by parvatijay2901** [comment]
Got it! Thanks @anujsinha3
