### ISSUE TITLE
refactor: Change internal local imports to be relative

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/MAWpy#81]
I noticed that the code has a lot of absolute imports for `mawpy`. This can be problematic if at some point the package name change for some reason. See

https://github.com/uw-ssec/MAWpy/blob/f5cda5d88f4150a8a5684ecc07a9b31d62703903/src/mawpy/steps/incremental_clustering.py#L19-L24

I highly recommend to protect this and reduce repetition in the code, let's do relative imports.

For example in the `incremental_clustering.py` code like above, the `mawpy` import can simply change to 

```python
 from ..constants import (USER_ID, STAY_DUR, ORIG_LAT, STAY_LAT, STAY_LONG, STAY_UNC, ORIG_LONG, ORIG_UNC, STAY, 
                              UNIX_START_T, IC_COLUMNS) 
 from ..distance import distance 
 from ..utilities.common import get_combined_stay, get_stay_groups 
 from ..utilities.cluster import Cluster 
 from ..utilities.preprocessing import get_preprocessed_dataframe, get_list_of_chunks_by_column, execute_parallel 
```

This is one example, but changes within the whole codebase need to happen for this. 😄

**Comment by anujsinha3** [comment]
Understood the brevity point. I have a quick question.

For relative imports, since it does not use an absolute path, this becomes fragile when files are moved around from one directory to another, right?

**Comment by lsetiawan** [comment]
A text from PEP8:

Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured (such as when a directory inside a package ends up on `sys.path`):

```
import mypkg.sibling
from mypkg import sibling
from mypkg.sibling import example
```

However, explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose:

```
from . import sibling
from .sibling import example
```
Standard library code should avoid complex package layouts and always use absolute imports.

My comment on this:
I doubt that this package will change naming anytime soon, so feel free to use absolute import. I personally like the relative one to decrease the verbosity and it's easier to change package names, and also make it clear that the section of relative import means that this is the local package.

**Comment by lsetiawan** [comment]
I've merged https://github.com/uw-ssec/MAWpy/pull/83 and that uses relative imports, whatever you decide, please ensure that it's consistent in the codebase 😄
